steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/foodie-fiesta-backend:$SHORT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/foodie-fiesta--backend:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "foodie-fiesta-backend",
        "--image=gcr.io/$PROJECT_ID/foodie-fiesta-backend:$SHORT_SHA",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-secrets",
        "MONGO_DB_URI=talk-to-celebrity-mongodb-uri:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
