steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/foodie-festa:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/foodie-festa:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "foodie-festa",
        "--image=gcr.io/$PROJECT_ID/foodie-festa:$SHORT_SHA",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-secrets",
        "FIREBASE_SERVICE_ACCOUNT=foodie-festa-service-account:latest,MONGO_USERNAME=foodie-festa-mongo-username:latest,MONGO_PASSWORD=foodie-festa-mongo-password:latest,MONGO_DATABASE_NAME=foodie-festa-mongo-database-name:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
