steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/foodie-festa-backend:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/foodie-festa-backend:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "foodie-festa-backend",
        "--image=gcr.io/$PROJECT_ID/foodie-festa-backend:$SHORT_SHA",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-secrets",
        "FIREBASE_SERVICE_ACCOUNT=foodie-festa-service-account:latest,MONGO_DB_URI=foodie-festa-mongo-uri:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
